### ISSUE TITLE
503 on https://skohub.io/editor/

### ISSUE THREAD

**Issue by jschnasse** [skohub-io/skohub-editor#96]
Hello folks,

seems that the editor is not available at the moment?
I´m getting a 503 at https://skohub.io/editor/

Best regards
Jan

**Comment by acka47** [comment]
We shut it down in March due to missing resources and have been focusing on the one SkoHub module that is actually used in production settings: SkoHub Vocabs. See also https://blog.skohub.io/2020-03-31-skohub-editor/. Apparently, we haven't updated skohub.io accordingly. Will leave this ticket open to take care of it.

**Comment by acka47** [comment]
In the meantime, I removed the link to the editor from skohub.io. Closing
